<?php
$module_lang = array(
  'allimages' => 'All images',
  'author' => 'Author',
  'befirst' => 'Be the first to add an image',
  'back' => 'Back',
  'cancel' => 'Reset form',
  'comment' => 'Comment',
  'delete' =>'Delete',
  'title' => 'Gallery',
  'date' => 'Date',
  'deleteconfirm' => 'Are you sure you want to delete this image?',
  'deleted' => 'Deleted',
  'deletesuccess' => 'Your picture has been removed from the gallery. The site admin will now have to purge the pitcure from the system.',
  'edit' => 'Edit',
  'editsuccess' => 'Your picture has been edited.',
  'ErrorFilename' => 'Sorry we already have a file by that name... Please rename your file and try again.',
  'file' => 'file',
  'filesize' => 'Max File size',
  'filetype' => 'File Type',
  'gallery' => 'Gallery',
  'galtype' => 'Screen or Wallpaper?',
  'home' => 'Gallery home',
  'images' => 'images',
  'inthegallery' => 'in the gallery',
  'mustlogin' => 'You must be logged in to do this.<br/>Please log in at the top of the screan.',
  'next' => 'Next',
  'noimages' => 'Therer are currently no images in this category',
  'nonfiletype' => 'The flie type is not supported',
  'nopictoedit' => 'You tried to cheat!! But you forgot to include and image.',
  'notowneredit' => 'Nice try, but you don\'t have privlages to edit this image!',
  'upload'=> 'Upload',
  'Uploaderror' => '<b><color=red>Error!</color></b> Could not upload or move the file!',
  'username' => 'User Name',
  'selecttype' => "You didn't Select a category for your image",
  // CATEGORRY NAME TRANSLATIONS HERE   <------------<<<<
  'screenshot' => 'Screenshot',
  'wallpaper' => 'Wallpaper',
  'userart' => 'User art',
  'addyourown' => 'Add your Own'//,
  //'newcat' => 'New Category'
);